# Basis-Image verwenden
FROM python:3.10-slim

# Erstelle ein Verzeichnis für die Python-Skripte
RUN mkdir -p /app /app/logs /etc/mosquitto /mosquitto/config

WORKDIR /app

# Systemabhängigkeiten installieren
RUN apt-get update && apt-get install -y \
	git \
    openssh-server \
    vim \
    nano \
    logrotate \
    supervisor \
	mosquitto \
    && rm -rf /var/lib/apt/lists/*

# clone GitHub-Repository
RUN git clone --branch moonraker-fritz https://github.com/SirRenix/FritzDectMQTT.git /app/FritzDectMQTT

#set work directory for FritzDectMQTT
WORKDIR /app/FritzDectMQTT

# Installiere die Python-Abhängigkeiten für FritzDectMQTT aus der geklonten requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# copy Logrotate-config
COPY /docker/fritzdectmqttdocker.logrotate /etc/logrotate.d/fritzdectmqtt

# Mosquitto Konfiguration
COPY /docker/mosquitto.conf /mosquitto/config/mosquitto.conf

# Kopiere Supervisor-Konfiguration
COPY /docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Erstelle einen Mosquitto-Benutzer mit Passwort
RUN mosquitto_passwd -b /mosquitto/config/mosquitto.passwd yourusername yourpassword

# SSH Konfiguration
RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

# Exponierte Ports
EXPOSE 22 1883

# Starten von Supervisor (mit SSH, logrotate und FritzDectMQTT)
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]